import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Building2, ClipboardCheck, FileText, LogOut, Plus, ShieldCheck, Users } from 'lucide-react';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const roles = ['super_admin','admin','engenheiro_construtora','engenheiro_empreiteira','mestre_obras','encarregado'];
const statusDoc = ['rascunho','finalizado','aprovado'];

function App(){
  const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [page,setPage]=useState('dashboard'); const [loading,setLoading]=useState(true);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
  useEffect(()=>{ if(session?.user) loadProfile(); else setProfile(null)},[session]);
  async function loadProfile(){ const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).single(); setProfile(data); }
  if(loading) return <div className="center">Carregando...</div>;
  if(!session) return <Auth/>;
  if(!profile) return <div className="center">Perfil ainda não criado. Saia e entre novamente.</div>;
  if(profile.status!=='approved') return <Pending email={session.user.email}/>;
  return <Shell page={page} setPage={setPage} profile={profile} session={session} reloadProfile={loadProfile}/>;
}
function Pending({email}){return <div className="center card small"><h1>Cadastro pendente</h1><p>{email}</p><p>Peça para o administrador aprovar seu acesso no Supabase, tabela <b>profiles</b>.</p><button onClick={()=>supabase.auth.signOut()}>Sair</button></div>}
function Auth(){ const [mode,setMode]=useState('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [msg,setMsg]=useState(''); async function submit(e){e.preventDefault(); setMsg('Processando...'); if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password}); setMsg(error?error.message:'Entrando...')} else {const {error}=await supabase.auth.signUp({email,password,options:{data:{name}}}); setMsg(error?error.message:'Cadastro criado. Faça login e aguarde aprovação.')}} return <div className="auth"><form className="card authbox" onSubmit={submit}><h1>AVG Obras</h1><p>RDO, FVS, fotos e PDF.</p>{mode==='cadastro'&&<input placeholder="Nome completo" value={name} onChange={e=>setName(e.target.value)} required/>}<input placeholder="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{mode==='login'?'Entrar':'Cadastrar'}</button><a onClick={()=>setMode(mode==='login'?'cadastro':'login')}>{mode==='login'?'Criar cadastro':'Já tenho cadastro'}</a><small>{msg}</small></form></div>}
function Shell({page,setPage,profile,session}){ const menu=[['dashboard','Painel',Building2],['obras','Obras',Building2],['rdos','RDOs',FileText],['fvs','FVS',ClipboardCheck],['profissionais','Profissionais',Users],['admin','Admin',ShieldCheck]]; return <div className="app"><aside><h2>AVG Obras</h2><p>{profile.name||session.user.email}</p>{menu.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={18}/>{label}</button>)}<button onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Sair</button></aside><main>{page==='dashboard'&&<Dashboard/>}{page==='obras'&&<Obras/>}{page==='rdos'&&<Docs type="rdo"/>}{page==='fvs'&&<Docs type="fvs"/>}{page==='profissionais'&&<Profissionais/>}{page==='admin'&&<Admin/>}</main></div>}
function Dashboard(){ const [counts,setCounts]=useState({obras:0,rdos:0,fvs:0}); useEffect(()=>{Promise.all(['obras','rdos','fvs'].map(t=>supabase.from(t).select('id',{count:'exact',head:true}))).then(r=>setCounts({obras:r[0].count||0,rdos:r[1].count||0,fvs:r[2].count||0}))},[]); return <><Header title="Painel de controle"/><div className="grid3"><Stat t="Obras" n={counts.obras}/><Stat t="RDOs" n={counts.rdos}/><Stat t="FVS" n={counts.fvs}/></div><div className="card"><h3>Fluxo recomendado</h3><p>Cadastre a obra, cadastre profissionais, registre o RDO/FVS com fotos, finalize e gere o PDF para arquivamento.</p></div></>}
function Stat({t,n}){return <div className="card stat"><span>{t}</span><b>{n}</b></div>}
function Header({title,children}){return <div className="header"><h1>{title}</h1>{children}</div>}
function Obras(){ const empty={nome:'',construtora:'',endereco:'',cidade:'',responsavel_tecnico:'',status:'ativa',data_inicio:'',previsao_termino:'',observacoes:''}; return <Crud title="Obras" table="obras" empty={empty} fields={Object.keys(empty)}/> }
function Profissionais(){ const empty={nome:'',funcao:'',telefone:'',obra_id:'',status:'ativo'}; return <Crud title="Profissionais" table="profissionais" empty={empty} fields={Object.keys(empty)}/> }
function Crud({title,table,empty,fields}){ const [items,setItems]=useState([]),[form,setForm]=useState(empty),[show,setShow]=useState(false); useEffect(()=>{load()},[]); async function load(){const {data}=await supabase.from(table).select('*').order('created_at',{ascending:false}); setItems(data||[])} async function save(e){e.preventDefault(); await supabase.from(table).insert(form); setForm(empty); setShow(false); load()} return <><Header title={title}><button onClick={()=>setShow(!show)}><Plus size={18}/>Novo</button></Header>{show&&<form className="card form" onSubmit={save}>{fields.map(f=><label key={f}>{f}<input value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>)}<button>Salvar</button></form>}<div className="list">{items.map(i=><div className="card row" key={i.id}><b>{i.nome||i.servico||i.id}</b><small>{i.construtora||i.funcao||i.status}</small></div>)}</div></>}
function Docs({type}){ const table=type==='rdo'?'rdos':'fvs'; const title=type==='rdo'?'RDOs - Relatório Diário de Obra':'FVS - Ficha de Verificação de Serviço'; const [items,setItems]=useState([]),[obras,setObras]=useState([]),[show,setShow]=useState(false); const base=type==='rdo'?{obra_id:'',data:'',responsavel:'',clima_manha:'',clima_tarde:'',clima_noite:'',equipe:'',qtd_funcionarios:'',servicos_executados:'',servicos_nao_executados:'',motivo_atraso:'',materiais_recebidos:'',equipamentos:'',ocorrencias:'',nao_conformidades:'',observacoes:'',status:'rascunho'}:{obra_id:'',data:'',responsavel:'',local:'',servico:'',criterios:'',resultado:'aprovado',acao_corretiva:'',prazo_correcao:'',responsavel_correcao:'',observacoes:'',status:'rascunho'}; const [form,setForm]=useState(base); const [files,setFiles]=useState([]); useEffect(()=>{load(); supabase.from('obras').select('*').then(({data})=>setObras(data||[]))},[]); async function load(){const {data}=await supabase.from(table).select('*, obras(nome,construtora)').order('created_at',{ascending:false}); setItems(data||[])} async function uploadFotos(docId){for(const f of files){const path=`${type}/${docId}/${Date.now()}-${f.name}`; const up=await supabase.storage.from('fotos').upload(path,f); if(!up.error){const {data:{publicUrl}}=supabase.storage.from('fotos').getPublicUrl(path); await supabase.from(type==='rdo'?'rdo_fotos':'fvs_fotos').insert({[`${type}_id`]:docId,url:publicUrl,legenda:f.name})}}} async function save(e){e.preventDefault(); const payload={...form,qtd_funcionarios: form.qtd_funcionarios?Number(form.qtd_funcionarios):null}; const {data,error}=await supabase.from(table).insert(payload).select().single(); if(error){alert(error.message);return} await uploadFotos(data.id); setForm(base); setFiles([]); setShow(false); load()} return <><Header title={title}><button onClick={()=>setShow(!show)}><Plus size={18}/>Novo</button></Header>{show&&<form className="card form" onSubmit={save}><label>Obra<select value={form.obra_id} onChange={e=>setForm({...form,obra_id:e.target.value})} required><option value="">Selecione</option>{obras.map(o=><option key={o.id} value={o.id}>{o.nome}</option>)}</select></label>{Object.keys(base).filter(k=>k!=='obra_id').map(k=><label key={k}>{k}{k==='status'?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{statusDoc.map(s=><option key={s}>{s}</option>)}</select>:<textarea rows={k==='observacoes'||k.includes('servicos')||k.includes('ocorrencias')?4:1} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}<label>Fotos<input type="file" multiple accept="image/*" onChange={e=>setFiles([...e.target.files])}/></label><button>Salvar</button></form>}<div className="list">{items.map(i=><DocCard key={i.id} item={i} type={type}/>)}</div></>}
function DocCard({item,type}){ async function pdf(){ const fotoTable=type==='rdo'?'rdo_fotos':'fvs_fotos'; const fk=`${type}_id`; const {data:fotos}=await supabase.from(fotoTable).select('*').eq(fk,item.id); const el=document.createElement('div'); el.className='pdf'; el.innerHTML=`<h1>AVG Construção Civil LTDA</h1><h2>${type==='rdo'?'Relatório Diário de Obra':'Ficha de Verificação de Serviço'}</h2><p><b>Obra:</b> ${item.obras?.nome||''} - ${item.obras?.construtora||''}</p><p><b>Data:</b> ${item.data||''}</p><p><b>Responsável:</b> ${item.responsavel||''}</p>${Object.entries(item).filter(([k])=>!['id','created_at','obra_id','obras'].includes(k)).map(([k,v])=>`<p><b>${k}:</b> ${v||''}</p>`).join('')}<h3>Relatório fotográfico</h3><div class="photos">${(fotos||[]).map(f=>`<div><img src="${f.url}"/><small>${f.legenda||''}</small></div>`).join('')}</div><br/><p>Assinatura: ____________________________________</p>`; document.body.appendChild(el); const canvas=await html2canvas(el,{scale:2,useCORS:true}); const img=canvas.toDataURL('image/png'); const doc=new jsPDF('p','mm','a4'); const w=210,h=canvas.height*210/canvas.width; doc.addImage(img,'PNG',0,0,w,h); doc.save(`${type}-${item.data||item.id}.pdf`); el.remove(); } return <div className="card row"><div><b>{item.obras?.nome||'Sem obra'}</b><small>{item.data} • {item.status}</small></div><button onClick={pdf}>Gerar PDF</button></div>}
function Admin(){ const [users,setUsers]=useState([]); useEffect(()=>{load()},[]); async function load(){const {data}=await supabase.from('profiles').select('*').order('created_at',{ascending:false}); setUsers(data||[])} async function upd(id,patch){await supabase.from('profiles').update(patch).eq('id',id); load()} return <><Header title="Administração"/><div className="list">{users.map(u=><div className="card admin" key={u.id}><b>{u.name||u.email}</b><select value={u.role} onChange={e=>upd(u.id,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><select value={u.status} onChange={e=>upd(u.id,{status:e.target.value})}><option value="pending">pending</option><option value="approved">approved</option><option value="disabled">disabled</option></select></div>)}</div></>}
createRoot(document.getElementById('root')).render(<App/>);
