create extension if not exists "uuid-ossp";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,email text,name text,role text default 'mestre_obras',status text default 'pending',created_at timestamptz default now());
create table if not exists public.obras (id uuid primary key default uuid_generate_v4(),nome text not null,construtora text,endereco text,cidade text,responsavel_tecnico text,status text default 'ativa',data_inicio date,previsao_termino date,observacoes text,created_at timestamptz default now());
create table if not exists public.profissionais (id uuid primary key default uuid_generate_v4(),nome text not null,funcao text,telefone text,obra_id uuid references public.obras(id) on delete set null,status text default 'ativo',created_at timestamptz default now());
create table if not exists public.user_obras (id uuid primary key default uuid_generate_v4(),user_id uuid references public.profiles(id) on delete cascade,obra_id uuid references public.obras(id) on delete cascade,created_at timestamptz default now(),unique(user_id,obra_id));
create table if not exists public.rdos (id uuid primary key default uuid_generate_v4(),obra_id uuid references public.obras(id) on delete cascade,data date,responsavel text,clima_manha text,clima_tarde text,clima_noite text,equipe text,qtd_funcionarios integer,servicos_executados text,servicos_nao_executados text,motivo_atraso text,materiais_recebidos text,equipamentos text,ocorrencias text,nao_conformidades text,observacoes text,status text default 'rascunho',created_at timestamptz default now());
create table if not exists public.rdo_fotos (id uuid primary key default uuid_generate_v4(),rdo_id uuid references public.rdos(id) on delete cascade,url text,legenda text,created_at timestamptz default now());
create table if not exists public.fvs (id uuid primary key default uuid_generate_v4(),obra_id uuid references public.obras(id) on delete cascade,data date,responsavel text,local text,servico text,criterios text,resultado text,acao_corretiva text,prazo_correcao date,responsavel_correcao text,observacoes text,status text default 'rascunho',created_at timestamptz default now());
create table if not exists public.fvs_itens (id uuid primary key default uuid_generate_v4(),fvs_id uuid references public.fvs(id) on delete cascade,item text,status text,observacao text,created_at timestamptz default now());
create table if not exists public.fvs_fotos (id uuid primary key default uuid_generate_v4(),fvs_id uuid references public.fvs(id) on delete cascade,url text,legenda text,created_at timestamptz default now());

insert into public.obras(nome,construtora,status) values ('Wonder of The Seas','Construtora GPC','ativa'),('House','Construtora UP','ativa') on conflict do nothing;
insert into public.profissionais(nome,status) values ('Everton Branco de Souza','ativo'),('Antoni Vanderlei Moraes','ativo'),('Antonio Alberto Parra Vericoto','ativo'),('Sandro dos Santos','ativo'),('Henry Amarilla','ativo'),('Alan Souza Carvalho','ativo'),('Daniel Alves dos Santos','ativo'),('Luciano Francisco da Silva','ativo'),('Edivan De Oliveira Gomes','ativo'),('Marcelo Gomes dos Santos','ativo'),('Fariz Alexis Pina Contreras','ativo'),('Simão Bispo','ativo'),('Abimael Bispo','ativo') on conflict do nothing;

create or replace function public.handle_new_user() returns trigger as $$ begin insert into public.profiles(id,email,name) values (new.id,new.email,coalesce(new.raw_user_meta_data->>'name','')) on conflict(id) do nothing; return new; end; $$ language plpgsql security definer;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security; alter table public.obras enable row level security; alter table public.profissionais enable row level security; alter table public.user_obras enable row level security; alter table public.rdos enable row level security; alter table public.rdo_fotos enable row level security; alter table public.fvs enable row level security; alter table public.fvs_itens enable row level security; alter table public.fvs_fotos enable row level security;

drop policy if exists "profiles read authenticated" on public.profiles; create policy "profiles read authenticated" on public.profiles for select to authenticated using (true);
drop policy if exists "profiles update admin" on public.profiles; create policy "profiles update admin" on public.profiles for update to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('super_admin','admin')) or id=auth.uid());

do $$ declare t text; begin foreach t in array array['obras','profissionais','user_obras','rdos','rdo_fotos','fvs','fvs_itens','fvs_fotos'] loop execute format('drop policy if exists "read approved %s" on public.%I',t,t); execute format('create policy "read approved %s" on public.%I for select to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.status=''approved''))',t,t); execute format('drop policy if exists "write approved %s" on public.%I',t,t); execute format('create policy "write approved %s" on public.%I for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.status=''approved'')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.status=''approved''))',t,t); end loop; end $$;
